language: python
python:
  - "3.4"
  - "2.7"
  - "pypy"
  - "2.6"
  - "3.3"
# command to install dependencies
install: pip install -r requirements-tests.txt
# command to run tests, e.g. python setup.py test
script: py.test tests
